### ISSUE TITLE
Having a lot of issues on all machines

### ISSUE THREAD

**Issue by ORESoftware** [stephenwvickers/node-net-ping#14]
I have issues with this module on Mac, Windows and Linux

here is the Maven output from a Jenkins build today:

```
[INFO] Building smartconnect 0.0.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2:exec (exec-check-deps) @ smartconnect ---
[INFO] 
[INFO] --- exec-maven-plugin:1.2:exec (exec-npm-install) @ smartconnect ---
npm WARN package.json smartconnect@0.0.2 No license field.
npm WARN package.json Dependency 'debug' exists in both dependencies and devDependencies, using 'debug@^2.2.0' from dependencies
npm WARN package.json Dependency 'expect' exists in both dependencies and devDependencies, using 'expect@^1.13.0' from dependencies
npm WARN package.json Dependency 'mocha' exists in both dependencies and devDependencies, using 'mocha@^2.3.4' from dependencies
npm WARN package.json Dependency 'nock' exists in both dependencies and devDependencies, using 'nock@^2.18.2' from dependencies
npm WARN package.json Dependency 'nodejs-dep-check' exists in both dependencies and devDependencies, using 'nodejs-dep-check@^1.2.2' from dependencies
npm WARN deprecated exec@0.2.1: deprecated in favor of builtin child_process.execFile
npm WARN peerDependencies The peer dependency continuation-local-storage@~3 included from cls-bluebird will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})

> dtrace-provider@0.6.0 install /home/jenkins/workspace/csv-smartconnect-x86_64-rel/nodejs/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN optional dep failed, continuing fsevents@1.0.6

> expect@1.13.4 postinstall /home/jenkins/workspace/csv-smartconnect-x86_64-rel/nodejs/node_modules/expect
> node ./npm-scripts/postinstall.js


> raw-socket@1.4.0 install /home/jenkins/workspace/csv-smartconnect-x86_64-rel/nodejs/node_modules/suman/node_modules/net-ping/node_modules/raw-socket
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 533, in script_main
    return main(sys.argv[1:])
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 526, in main
    return gyp_main(args)
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 502, in gyp_main
    params, options.check, options.circular_check)
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2736, in Load
    variables, includes, depth, check, True)
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 386, in LoadTargetBuildFile
    includes, True, check)
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 238, in LoadOneBuildFile
    None)
  File "binding.gyp", line 1
    {
     ^
SyntaxError: invalid syntax
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32-279.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jenkins/workspace/csv-smartconnect-x86_64-rel/nodejs/node_modules/suman/node_modules/net-ping/node_modules/raw-socket
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

> node-expat@2.3.12 install /home/jenkins/workspace/csv-smartconnect-x86_64-rel/nodejs/node_modules/xml2json/node_modules/node-expat
> node-gyp rebuild

make: Entering directory `/home/jenkins/workspace/csv-smartconnect-x86_64-rel/nodejs/node_modules/xml2json/node_modules/node-expat/build'
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  AR(target) Release/obj.target/deps/libexpat/libexpat.a
  COPY Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
  SOLINK_MODULE(target) Release/obj.target/node_expat.node
  COPY Release/node_expat.node
make: Leaving directory `/home/jenkins/workspace/csv-smartconnect-x86_64-rel/nodejs/node_modules/xml2json/node_modules/node-expat/build'
npm ERR! Linux 2.6.32-279.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! raw-socket@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the raw-socket@1.4.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the raw-socket package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls raw-socket
npm ERR! There is likely additional logging output above.
```

do you know about any such problem?

**Comment by stephenwvickers** [comment]
Hi,

Can you send output of "python -V"?

Thanks

Steve

**Comment by ORESoftware** [comment]
will do as soon as I get back to that machine thanks

**Comment by viion** [comment]
Also having similiar issue, python -V = 3.4.0, so I cannot install this module.

```
E:\BNS>npm install net-ping

> raw-socket@1.4.0 install E:\BNS\node_modules\raw-socket
> node-gyp rebuild


E:\BNS\node_modules\raw-socket>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.4.0, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:121:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:110:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:821:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\BNS\node_modules\raw-socket
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:raw-socket@1.4.0 raw-socket@1.4.0 install: `node-gyp rebuild`
npm WARN install:raw-socket@1.4.0 Exit status 1

E:\BNS>
```

**Comment by stephenwvickers** [comment]
Hi Viion,

Node that Python 3.x is not supported by node-gyp:

https://github.com/nodejs/node-gyp#installation

This is actually mentioned in your error above:

```
gyp ERR! stack Error: Python executable "python" is v3.4.0, which is not supported by gyp.
```

Steve

**Comment by stephenwvickers** [comment]
No more information from user.
