### ISSUE TITLE
Error NodeJS v5.5.0

### ISSUE THREAD

**Issue by ddesna** [stephenwvickers/node-net-ping#15]
I get this error with net-ping 1.1.12 and Node 5.5.0

```
module.js:440
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 47, got 14.
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/Dani/NodeJS-Tuts/snmp-agent/node_modules/net-ping/node_modules/raw-socket/index.js:4:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

**Comment by stephenwvickers** [comment]
Hi,

It looks like the version of node your raw-socket module was compiled for is different from the node version under which it is actually being run.

Steve

**Comment by ddesna** [comment]
@stephenwvickers which version of node do you recommended for net-ping ?

**Comment by stephenwvickers** [comment]
That's not what I meant :)

The net-ping module depends on the raw-socket module (also maintained by me), and this is a C++ add-on and must be compiled to be used since it is C++ code.

It appears that the raw-socket module was installed (i.e. compiled) with one version of node, then moved to another host which runs a different version of node.

Or, the version of node on the affected host has been upgraded since the original installation of raw-socket, and raw-socket was not re-installed.

Steve

**Comment by ddesna** [comment]
You are right @stephenwvickers ! Thnx ;)
I just reinstall net-ping and now it's working properly.
