### ISSUE TITLE
Error: Cannot find module 'footprint'

### ISSUE THREAD

**Issue by HugHoo** [stephenwvickers/node-net-ping#27]
First time using node-net-ping, and failed.

Node.js version: v6.3.1

Error stack trace:

```
Error: Cannot find module 'footprint'                                                                                        
    at Function.Module._resolveFilename (module.js:440:15)                                                                   
    at Function.Module._load (module.js:388:25)                                                                              
    at Module.require (module.js:468:17)                                                                                     
    at require (internal/module.js:20:19)                                                                                    
    at Object.<anonymous> (D:\GitRepos\node-ping-vps\node_modules\node-ping\context.js:3:17)                                 
    at Module._compile (module.js:541:32)                                                                                    
    at Object.Module._extensions..js (module.js:550:10)                                                                      
    at Module.load (module.js:458:32)                                                                                        
    at tryModuleLoad (module.js:417:12)                                                                                      
    at Function.Module._load (module.js:409:3)   
```

**Comment by stephenwvickers** [comment]
Hi,

You should open a ticket with the authors of the `node-ping` module.

Thanks

Steve
