### ISSUE TITLE
getting some npm spewage for "raw-socket"

### ISSUE THREAD

**Issue by ORESoftware** [stephenwvickers/node-net-ping#31]
Looks like this lib depends on "raw-socket", according to npm ls / npm la command like so:

```
oleg@xps:~/WebstormProjects/oresoftware/suman$ npm la raw-socket
suman@1.1.512206
│ /home/oleg/WebstormProjects/oresoftware/suman
│ Suman is a next-generation Node.js test runner designed to supercede Mocha and rival AVA
│ git+https://github.com/ORESoftware/suman.git
│ https://github.com/ORESoftware/suman#readme
└─┬ net-ping@1.2.0
  │ Ping and trace route to many hosts at once.
  │ git://github.com/stephenwvickers/node-net-ping.git
  │ https://github.com/stephenwvickers/node-net-ping#readme
  └── raw-socket@1.5.1 
      Raw sockets for Node.js.
      git://github.com/stephenwvickers/node-raw-socket.git
      https://github.com/stephenwvickers/node-raw-socket#readme
```

the problem I am having is that "raw-socket" has some node-gyp warnings:

```
> raw-socket@1.5.1 install /home/oleg/WebstormProjects/oresoftware/curtain/node_modules/raw-socket
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/oleg/WebstormProjects/oresoftware/curtain/node_modules/raw-socket/build'
  CXX(target) Release/obj.target/raw/src/raw.o
../src/raw.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE raw::CreateChecksum(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/raw.cc:70:43: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
  uint32_t start_with = info[0]->ToUint32 ()->Value ();
                                           ^
In file included from /home/oleg/.node-gyp/7.2.1/include/node/node.h:42:0,
                 from ../src/raw.h:21,
                 from ../src/raw.cc:6:
/home/oleg/.node-gyp/7.2.1/include/node/v8.h:8436:15: note: declared here
 Local<Uint32> Value::ToUint32() const {
               ^
../src/raw.cc:92:31: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   offset = info[2]->ToUint32 ()->Value ();
                               ^
In file included from /home/oleg/.node-gyp/7.2.1/include/node/node.h:42:0,
                 from ../src/raw.h:21,
                 from ../src/raw.cc:6:
/home/oleg/.node-gyp/7.2.1/include/node/v8.h:8436:15: note: declared here
 Local<Uint32> Value::ToUint32() const {
               ^
../src/raw.cc:104:48: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   unsigned int new_length = info[3]->ToUint32 ()->Value ();
                                                ^
In file included from /home/oleg/.node-gyp/7.2.1/include/node/node.h:42:0,
                 from ../src/raw.h:21,
                 from ../src/raw.cc:6:
/home/oleg/.node-gyp/7.2.1/include/node/v8.h:8436:15: note: declared here
 Local<Uint32> Value::ToUint32() const {
               ^
../src/raw.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE raw::Htonl(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/raw.cc:133:43: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
  unsigned int number = info[0]->ToUint32 ()->Value ();
                                           ^
In file included from /home/oleg/.node-gyp/7.2.1/include/node/node.h:42:0,
                 from ../src/raw.h:21,
                 from ../src/raw.cc:6:
/home/oleg/.node-gyp/7.2.1/include/node/v8.h:8436:15: note: declared here
 Local<Uint32> Value::ToUint32() const {
               ^
../src/raw.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE raw::Htons(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/raw.cc:152:43: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
  unsigned int number = info[0]->ToUint32 ()->Value ();
                                           ^
In file included from /home/oleg/.node-gyp/7.2.1/include/node/node.h:42:0,
                 from ../src/raw.h:21,
                 from ../src/raw.cc:6:
/home/oleg/.node-gyp/7.2.1/include/node/v8.h:8436:15: note: declared here
 Local<Uint32> Value::ToUint32() const {
               ^
../src/raw.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE raw::Ntohl(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/raw.cc:177:43: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
  unsigned int number = info[0]->ToUint32 ()->Value ();
                                           ^
In file included from /home/oleg/.node-gyp/7.2.1/include/node/node.h:42:0,
                 from ../src/raw.h:21,
                 from ../src/raw.cc:6:
/home/oleg/.node-gyp/7.2.1/include/node/v8.h:8436:15: note: declared here
 Local<Uint32> Value::ToUint32() const {
               ^
../src/raw.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE raw::Ntohs(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/raw.cc:196:43: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
  unsigned int number = info[0]->ToUint32 ()->Value ();
                                           ^
In file included from /home/oleg/.node-gyp/7.2.1/include/node/node.h:42:0,
                 from ../src/raw.h:21,
                 from ../src/raw.cc:6:
/home/oleg/.node-gyp/7.2.1/include/node/v8.h:8436:15: note: declared here
 Local<Uint32> Value::ToUint32() const {
               ^
../src/raw.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE raw::SocketWrap::GetOption(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/raw.cc:377:32: warning: ‘v8::Local<v8::Int32> v8::Value::ToInt32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
  int level = info[0]->ToInt32 ()->Value ();
                                ^
In file included from /home/oleg/.node-gyp/7.2.1/include/node/node.h:42:0,
                 from ../src/raw.h:21,
                 from ../src/raw.cc:6:
/home/oleg/.node-gyp/7.2.1/include/node/v8.h:8442:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^
../src/raw.cc:378:33: warning: ‘v8::Local<v8::Int32> v8::Value::ToInt32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
  int option = info[1]->ToInt32 ()->Value ();
                                 ^
In file included from /home/oleg/.node-gyp/7.2.1/include/node/node.h:42:0,
                 from ../src/raw.h:21,
                 from ../src/raw.cc:6:
/home/oleg/.node-gyp/7.2.1/include/node/v8.h:8442:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^
../src/raw.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE raw::SocketWrap::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/raw.cc:461:42: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   socket->protocol_ = info[0]->ToUint32 ()->Value ();
                                          ^
In file included from /home/oleg/.node-gyp/7.2.1/include/node/node.h:42:0,
                 from ../src/raw.h:21,
                 from ../src/raw.cc:6:
/home/oleg/.node-gyp/7.2.1/include/node/v8.h:8436:15: note: declared here
 Local<Uint32> Value::ToUint32() const {
               ^
../src/raw.cc:469:27: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
    if (info[1]->ToUint32 ()->Value () == 2)
                           ^
In file included from /home/oleg/.node-gyp/7.2.1/include/node/node.h:42:0,
                 from ../src/raw.h:21,
                 from ../src/raw.cc:6:
/home/oleg/.node-gyp/7.2.1/include/node/v8.h:8436:15: note: declared here
 Local<Uint32> Value::ToUint32() const {
               ^
../src/raw.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE raw::SocketWrap::Send(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/raw.cc:651:30: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
  offset = info[1]->ToUint32 ()->Value ();
                              ^
In file included from /home/oleg/.node-gyp/7.2.1/include/node/node.h:42:0,
                 from ../src/raw.h:21,
                 from ../src/raw.cc:6:
/home/oleg/.node-gyp/7.2.1/include/node/v8.h:8436:15: note: declared here
 Local<Uint32> Value::ToUint32() const {
               ^
../src/raw.cc:652:30: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
  length = info[2]->ToUint32 ()->Value ();
                              ^
In file included from /home/oleg/.node-gyp/7.2.1/include/node/node.h:42:0,
                 from ../src/raw.h:21,
                 from ../src/raw.cc:6:
/home/oleg/.node-gyp/7.2.1/include/node/v8.h:8436:15: note: declared here
 Local<Uint32> Value::ToUint32() const {
               ^
../src/raw.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE raw::SocketWrap::SetOption(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/raw.cc:715:32: warning: ‘v8::Local<v8::Int32> v8::Value::ToInt32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
  int level = info[0]->ToInt32 ()->Value ();
                                ^
In file included from /home/oleg/.node-gyp/7.2.1/include/node/node.h:42:0,
                 from ../src/raw.h:21,
                 from ../src/raw.cc:6:
/home/oleg/.node-gyp/7.2.1/include/node/v8.h:8442:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^
../src/raw.cc:716:33: warning: ‘v8::Local<v8::Int32> v8::Value::ToInt32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
  int option = info[1]->ToInt32 ()->Value ();
                                 ^
In file included from /home/oleg/.node-gyp/7.2.1/include/node/node.h:42:0,
                 from ../src/raw.h:21,
                 from ../src/raw.cc:6:
/home/oleg/.node-gyp/7.2.1/include/node/v8.h:8442:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^
../src/raw.cc:735:27: warning: ‘v8::Local<v8::Int32> v8::Value::ToInt32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   len = info[3]->ToInt32 ()->Value ();
                           ^
In file included from /home/oleg/.node-gyp/7.2.1/include/node/node.h:42:0,
                 from ../src/raw.h:21,
                 from ../src/raw.cc:6:
/home/oleg/.node-gyp/7.2.1/include/node/v8.h:8442:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^
../src/raw.cc:747:29: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   ival = info[2]->ToUint32 ()->Value ();
                             ^
In file included from /home/oleg/.node-gyp/7.2.1/include/node/node.h:42:0,
                 from ../src/raw.h:21,
                 from ../src/raw.cc:6:
/home/oleg/.node-gyp/7.2.1/include/node/v8.h:8436:15: note: declared here
 Local<Uint32> Value::ToUint32() const {
               ^
  SOLINK_MODULE(target) Release/obj.target/raw.node
  COPY Release/raw.node
make: Leaving directory '/home/oleg/WebstormProjects/oresoftware/curtain/node_modules/raw-socket/build'

```

I think I should take it up with the "raw-socket" folks, but maybe you can verify that my observations described above are true? thanks

**Comment by ORESoftware** [comment]
Oh LOL, I just realized you are the author of raw-socket as well, so then you are the right person to talk to for this, I think :)

**Comment by stephenwvickers** [comment]
Hi, I am looking into this.  I will update once I have more information.

**Comment by dmason30** [comment]
@stephenwvickers Any update?

@ORESoftware did you find a ping lib that worked?

**Comment by stephenwvickers** [comment]
@dmason30 Are you saying that the library is not working?

**Comment by dmason30** [comment]
It doesn't install for me (using yarn or npm) due to the error above.

**Comment by stephenwvickers** [comment]
@dmason30 i dont see any error, only warnings?

Which error are referring too?

**Comment by stephenwvickers** [comment]
@dmason30 Can you advise on what error you are referring to?

**Comment by mhykes** [comment]
I'm not sure if this is what @ORESoftware and @dmason30 were seeing.  I also am unable to install net-ping due to issues with building raw-socket.

I'm relatively new to Node, so please let me know if there is something silly I've overlooked.  Let me know if there are further troubleshooting steps I can do to help chase this issue down.

Thank you for the effort you put into building and maintaining these libraries.

---
**For isolation, I attempted to install raw-socket alone and got the following:**

```
c:\Users\Admin\Desktop\NODEJS\AutoEncode\AutoEncode\AutoEncode>npm install raw-socket

 > raw-socket@1.5.1 install c:\Users\Admin\Desktop\NODEJS\AutoEncode\AutoEncode\AutoEncode\node_modules\raw-socket
 > node-gyp rebuild


c:\Users\Admin\Desktop\NODEJS\AutoEncode\AutoEncode\AutoEncode\node_modules\raw-socket>if not defined npm_config_node_gyp (node "C:\Users\Admin\AppData\Roaming\nvm\v6.4.0\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  raw.cc
  win_delay_load_hook.c
C:\Users\Admin\AppData\Roaming\nvm\v6.4.0\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '
__pfnDliNotifyHook2': redefinition; different type modifiers [c:\Users\Admin\Desktop\NODEJS\AutoEncode\AutoEncode\AutoEncode\n
ode_modules\raw-socket\build\raw.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNotifyHook
  2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Admin\AppData\Roaming\nvm\v6.4.0\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Admin\\AppData\\Roaming\\nvm\\v6.4.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\Admin\Desktop\NODEJS\AutoEncode\AutoEncode\AutoEncode\node_modules\raw-socket
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN auto-encode@0.0.0 No repository field.
npm WARN auto-encode@0.0.0 No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "raw-socket"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! raw-socket@1.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raw-socket@1.5.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the raw-socket package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs raw-socket
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls raw-socket
npm ERR! There is likely additional logging output above.

```

**Comment by stephenwvickers** [comment]
This is a little late, but I believe your issue here is related to node-gyp using a Visual Studio version different to what you actually have.

This is not an issue with net-ping (more specifically raw-socket).

You could try using the `--msvs_version` argument to npm.  It looks like you have 2015 installed, so probably something like (untested):

```
npm install net-ping --msvs_version=2015
```
