### ISSUE TITLE
Error: connect ETIMEDOUT on local interface

### ISSUE THREAD

**Issue by ecarew** [stephenwvickers/node-net-ping#40]
While testing my new app on IPV4, on a local interface, I get the following error:
Error: connect ETIMEDOUT
    at Connection._handleConnectTimeout (/home/evan/node_modules/mysql/lib/Connection.js:419:13)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:188:7)
    at Socket._onTimeout (net.js:352:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
    --------------------
    at Protocol._enqueue (/home/evan/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/home/evan/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/home/evan/node_modules/mysql/lib/Connection.js:130:18)
    at connectToDatabase (/home/evan/Projects/Status/driver.js:26:11)
    at Object.<anonymous> (/home/evan/Projects/Status/driver.js:21:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by stephenwvickers** [comment]
That error in theory could never be generated by this module.  Also, the stack trace would suggest it has nothing to do with this module.
