### ISSUE TITLE
App threw an error during load

### ISSUE THREAD

**Issue by MarvinDrude** [stephenwvickers/node-net-ping#49]
Hey,

I installed net-ping and now everytime I want to start the app I get this error:

```
    App threw an error during load
    Error: DLL-Initialising failed
    \\?\C:\PATH\node_modules\raw-socket\build\Release\raw.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\PATH\node_modules\raw-socket\index.js:4:11)
    at Object.<anonymous> (C:\PATH\node_modules\raw-socket\index.js:218:3)
```

the build\release folder contains raw.node

**Comment by stephenwvickers** [comment]
The module builds and works when using it normally via npm install, so it appear to be a local issue to yourself.  You are going to have to do a bit of debugging to get further with this, the output given doesn't provide a lot to go on.
